context:
  version: "1.78.0"

package:
  name: oxlint
  version: ${{ version }}

source:
  url: https://github.com/oxc-project/oxc/archive/oxlint_v${{ version }}.tar.gz
  sha256: 33b195c87225d25ffe2552a6b37753f675ffb1b777593e8094c119395234686b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - oxlint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Linter for oxc
  homepage: https://github.com/oxc-project/oxc
  repository: https://github.com/oxc-project/oxc

extra:
  recipe-maintainers:
    - danielnachun
    - tdejager
